server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelservice
    username: postgres
    password: Anurodh@1708
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: hotel-service