#server:
#  port: 8083
#
#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017
#      database: ratingservice
#  application:
#    name: rating-service

#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true

spring:
  application:
    name: rating-service
  config:
    import: configserver:http://localhost:8888